### ISSUE TITLE
epoch16 bug

### ISSUE THREAD

**Issue by ajohlander** [irfu/irfu-matlab#18]
Time interval:

tStart = irf_time([2002 02 03 05 19 12]); %start time
tint = [tStart, tStart+12]; %time interval

local.c_read('E_Vec_xyz_ISR2__C3_CP_EFW_L2_E3D_INERT',tint) does not read 

data is stored locally

**Comment by ajohlander** [comment]
Now it reads data but the time stamps are incorrect. Time increases in steps of 1 second with ~25 data points with the same time value.

**Comment by thomas-nilsson-irfu** [comment]
Hi,
it appears to be a bug in the NASA supplied "spdfbreakdownepoch16c", which is used by irf_time when converting from "cdfepoch16" to "epoch". (called on by line 243 in +local/c_read.m). I have just filed a bug report with Michael and the rest of the cdf team so hopefully they will soon release a new compiled cdf patch.

**Comment by ajohlander** [comment]
Now it works. Thanks!
