### ISSUE TITLE
irf_plot for 'Data__C1_CP_PEA_PITCH_SPIN_DPFlux'

### ISSUE THREAD

**Issue by binlipric** [irfu/irfu-matlab#19]
Hej irfu-matlab,

The code

 irf_plot('Data__C1_CP_PEA_PITCH_SPIN_DPFlux','comp_dim1','comp',1);

can give a correct figure for PEACE data in 7.5 degrees.
BUT, if change 'comp',1 to  'comp',2 ,it has some problem...like following, did I use a wrong arguments?

irf_plot('Data__C1_CP_PEA_PITCH_SPIN_DPFlux','comp_dim1','comp',2);
  [warning: caa_load(127)] loading C1_CP_PEA_PITCH_SPIN_DPFlux from location:CAA/C1_CP_PEA_PITCH_SPIN_DPFlux\*.cdf
Index exceeds matrix dimensions.

Error in dataobj/plot (line 453)
      lab_2 = num2str(dep_x{comp_dim}.data(1,comp)',['%.2f ' dep_x{comp_dim}.units '\n']);

Error in irf_plot (line 192)
        ax = plot(caa_dataobject{1},caa_varname{1},original_args{:});

Tack ! 
Bin

**Comment by thomas-nilsson-irfu** [comment]
This issue should be solved with my latest commit, (which is currently in the "devel" branch and will make it into the next stable release of irfu-matlab).
