### ISSUE TITLE
It said that the IRBEM is not OK

### ISSUE THREAD

**Issue by Fenyutanchan** [irfu/irfu-matlab#40]
irfu-matlab version:  v1.13.2
Checking if you have latest irfu-matlab... YES:)
IRBEM .. not OK. Please, contact irfu!
Operating system is OK
Matlab version is OK
CDF_LEAPSECONDSTABLE is OK

matlab version= '9.2.0.538062 (R2017a)'
System version is Microsoft Windows Version 10.0.15063

**Comment by thomas-nilsson-irfu** [comment]
Dear @Fenyutanchan,

thank you for reporting this issue. 
The IRBEM package (included in [contrib/libirbem](https://github.com/irfu/irfu-matlab/blob/master/contrib/libirbem) originally from https://sourceforge.net/projects/irbem/) have presently only compiled support for unix system (that is Linux and Mac). If you do not presently need the IRBEM-LIB package, then this warning can be ignored and irfu-matlab can be used anyhow.


I will try to look into adding compiled mex files for Windows as well (from the Fortran code in IRBEM-LIB), or if that is unsuccessful then simply disable trying to run our checks of IRBEM on Windows machines.


With best regards,

Thomas Nilsson

**Comment by Fenyutanchan** [comment]
@thomas-nilsson-irfu Thank you very much.
