### ISSUE TITLE
Documentation: Example links on google site are broken

### ISSUE THREAD

**Issue by LimaKilo** [irfu/irfu-matlab#46]
The readme points to https://sites.google.com/site/irfumatlab/ for examples. That links back to github for the code for the examples, but the links are broken (the examples are now in the irf folder instead of the root dir)

**Comment by thomas-nilsson-irfu** [comment]
Dear @LimaKilo, thank you for making us aware of this issue.

I am assigning this to @vaivads as he is the one who last modified the google pages. @vaivads would you mind having a look to see if you could update the Google pages (at your convenience)?
And also while you are at it, the `alfven_shear45.gif` file located on our space.irfu.se server which is to be shown under "Plasma wave movies" should be accessed using https:// not http://

**Comment by vaivads** [comment]
fixed
