### ISSUE TITLE
About the PDist format data

### ISSUE THREAD

**Issue by zhang-chi-IGGCAS** [irfu/irfu-matlab#70]
Dear all.,
         I found that using the PDist type data to plot the velocity distribution more conviently. but I want to know whether it is also valid for other mission data? e.g., Cluster and  MAVEN.  How to make the PDist data if I have the theta, phi and energy data?  thank you!

Chi Zhang;
Best wishes;

**Comment by thomas-nilsson-irfu** [comment]
Dear @zhang-chi-IGGCAS,

sorry for the delayed reply. As I am not personally that familiar with the PDist function, and its limits and limitations, nor with Cluster & MAVEN data I am assigning this issue to @danbgraham who I hope can reply with a more details response.


As for the `PDist` itself, it does appear to have some construct support for `thete`, `phi` and `energy` data named "skymap", but I am not 100% sure if this is what you would have for other missions like Cluster and MAVEN.
https://github.com/irfu/irfu-matlab/blob/c7204744a027f619a5c5f55327bc3ee9158f6a85/PDist.m#L57-L61
