### ISSUE TITLE
MMS Energyspectrum

### ISSUE THREAD

**Issue by 01344240** [irfu/irfu-matlab#71]
Hi Everyone,
Is there a way to make plots of the ion/electron energyspectrum plots for MMS?
Thanks,
Paul.

**Comment by wyli1124** [comment]
Dear Paul,

         Firstly, you can load the ion distribution functions via:

       iDist = mms.get_data('PDi_fpi_brst_l2', Tint, 1);
          Here, Tint is the time interval, and 1 (not L) is the MMS
spacecraft you are interested.

         Then, you can make energy spectrum plots via:
          irf_spectrogram(iDist.deflux.omni.specrec, 'log');


Best regards,
Wenya

**Comment by 01344240** [comment]
Dear Wenya,

Thank you so much for this!

Paul.

From: Wenya ***@***.***>
Reply-To: irfu/irfu-matlab ***@***.***>
Date: Wednesday, 7 April 2021 at 02:45
To: irfu/irfu-matlab ***@***.***>
Cc: "Curtis, Paul" ***@***.***>, Author ***@***.***>
Subject: Re: [irfu/irfu-matlab] MMS Energyspectrum (#71)

This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.


Dear Paul,

Firstly, you can load the ion distribution functions via:

iDist = mms.get_data('PDi_fpi_brst_l2', Tint, 1);
Here, Tint is the time interval, and 1 (not L) is the MMS
spacecraft you are interested.

Then, you can make energy spectrum plots via:
irf_spectrogram(iDist.deflux.omni.specrec, 'log');


Best regards,
Wenya

**Comment by thomas-nilsson-irfu** [comment]
I'm considering this issue fixed and closing it now.
If anyone disagrees, feel free to reopen this issue.
