### ISSUE TITLE
problem in accessing mms data using irf-matlab (devel-branch)

### ISSUE THREAD

**Issue by Jujotinas** [irfu/irfu-matlab#89]
// TODO (you): please remove comments like this line and fill in this form as best you can, checking relevant boxes, etc.

### Step 1: Latest code?
- [x] This issue is present in the most recent code (i.e. after running ```git pull``` this is still a problem).

### Step 2: Describe your environment
 * irfu-matlab branch (e.g. ```master```, ```devel```): ____
 * Matlab version used (e.g. ```Matlab R2020b```): ____
 * Operating system (e.g. ```Windows 10```, ```Mac OS X 10.15.6```, ```Linux Ubuntu 20.04```): ____
 - [x] A 64-bit installation of Matlab was used.

### Step 3: Describe the problem
I am using irf-matlab devel package and wants to access mms data. For that I have referred the link,  https://github.com/irfu/irfu-matlab/issues/69, for accessing the data. After implementing all the solution as given in the issues #69, I still cannot access the data. I have made all the folders and subfolders as per https://lasp.colorado.edu/mms/sdc/public/about/browse-wrapper/ , and run mms.db_init() command in command window of matlab (R2022a), still the matrix appears as a blank matrix.
I have attached a picture of a issue that is occurring for reference.

  
![Capture](https://user-images.githubusercontent.com/91287888/158569733-9f07991e-1a2f-4f3d-8851-df3268625905.PNG)

**Comment by thomas-nilsson-irfu** [comment]
Dear @Jujotinas,

when you say that you run `mms.db_init()` do you mean you ran something like:  `mms.db_init('local_file_db','c:\Whatever\Your\Path\')` and that you have subfolders `mms1`, `mms2`, `mms3`, `mms4` in this example path `c:\Whatever\Your\Path\`. And in these subfolder do you have next level subfolders fgm and so on down to daily folders for burst data similar to how the folder structure is on the LASP system?

And secondly: have you downloaded a copy of the cdf files from LASP (or NASA) to their corresponding folder on your system? As it can be several 10s or even 100s of TB of data for MMS, (unlike Cluster), our scripts do not try to download any cdf files on your behalf as this could result in hours of waiting (during which your internet connection could be essentially saturated) and in worst case it could result in a completely filled hard disc on your machine.
